# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

one <- function() {
    .Call('_rcpptest_one', PACKAGE = 'rcpptest')
}

signC <- function(x) {
    .Call('_rcpptest_signC', PACKAGE = 'rcpptest', x)
}

sumC <- function(x) {
    .Call('_rcpptest_sumC', PACKAGE = 'rcpptest', x)
}

pdistC <- function(x, ys) {
    .Call('_rcpptest_pdistC', PACKAGE = 'rcpptest', x, ys)
}

rowSumsC <- function(x) {
    .Call('_rcpptest_rowSumsC', PACKAGE = 'rcpptest', x)
}

allC <- function(x) {
    .Call('_rcpptest_allC', PACKAGE = 'rcpptest', x)
}

