# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

one <- function() {
    .Call('_rcpptest_one', PACKAGE = 'rcpptest')
}

signC <- function(x) {
    .Call('_rcpptest_signC', PACKAGE = 'rcpptest', x)
}

sumC <- function(x, narm = TRUE) {
    .Call('_rcpptest_sumC', PACKAGE = 'rcpptest', x, narm)
}

pdistC <- function(x, ys) {
    .Call('_rcpptest_pdistC', PACKAGE = 'rcpptest', x, ys)
}

rowSumsC <- function(x) {
    .Call('_rcpptest_rowSumsC', PACKAGE = 'rcpptest', x)
}

allC <- function(x) {
    .Call('_rcpptest_allC', PACKAGE = 'rcpptest', x)
}

cumprodC <- function(x) {
    .Call('_rcpptest_cumprodC', PACKAGE = 'rcpptest', x)
}

diffC <- function(x, lag = 1L) {
    .Call('_rcpptest_diffC', PACKAGE = 'rcpptest', x, lag)
}

rangeC <- function(x) {
    .Call('_rcpptest_rangeC', PACKAGE = 'rcpptest', x)
}

sum3 <- function(x) {
    .Call('_rcpptest_sum3', PACKAGE = 'rcpptest', x)
}

sum4 <- function(x) {
    .Call('_rcpptest_sum4', PACKAGE = 'rcpptest', x)
}

medianC <- function(x) {
    .Call('_rcpptest_medianC', PACKAGE = 'rcpptest', x)
}

